services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qetr0265
      POSTGRES_DB: postgres
    ports:
      - 5432:5432